### ISSUE TITLE
Plugin One Wire: DS2438 Chip

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#240]
On documentaion, I saw this:

> DS2438 (battery monitor chip) is frequently used with a humidity sensor to read humidity by 1-wire network, or barometer, or solar sensor. For this chip, Yadoms provides all values : raw voltage, humidity, solar, barometer.

But I only have temperature device:

![yadom_0006](https://cloud.githubusercontent.com/assets/27768412/25537219/f5acd7d8-2c3d-11e7-85c4-4776705be83d.png)

I use the **/mnt/1wire/26.99E4F1000000/VAD** and **/mnt/1wire/26.99E4F1000000/vis** input with DIY sensor and I have to apply a formula to convert the voltage into real value like luminosity, humidity or other..

I don't know if it's possible for yadom in new features to apply a formula and choose the device type (luminosity, humidity, temperature ...)

yadoms-raspberrypi-2.0.0-rc.2

**Comment by sgallou** [comment]
Ok, first documentation is wrong : DS2438 always give temperature, but other data depends of what is in MultiSensor/type OWFS folder :
* MS-TH add humidity
* MS-TL add Light
It seems that is not a good idea, because if I understand well documentation, only  iButtonLink’s multiSensor give the information.

OneWire plugin was written before Yadoms supports device configuration. So choice was made that try to discover data to acquire, or by default acquire all possible data.

Today, device configuration is supported, so configuration of the data to acquire (temperature, humidity and light) can be added, as well as apply linear formula (with 2 parameters, coefficient and offset). Maybe a more complex formula could be configured, but in this case we have to interpret the user formula (maybe by calling Python ?).
Can you add it in the forum wish list please, it's an intersting function to have.
For now, I will try to add a minimal configuration for this device.
