### ISSUE TITLE
ZWave wall plug "Oveload safety switch" problems

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#248]
The ZWave "FGWPE Wall Plug" has an "Oveload safety switch" value (overload, I suppose).

- There is no default value (the first time) for it
- the "Default setting: 65535" in the comment is wrong because it says "La valeur ne peut être supérieure à 32767"
- it doens't save the value (value empty when I open the configuration window again) <- this is not cool because it refuses to save the form if it is empty!

**Comment by jano42** [comment]
Ok this problem is due to Fibaro which do not respect ZWave specs !

https://github.com/OpenZWave/open-zwave/issues/229

All ZWave values must be unsignedn so a short is expected to be in range  (-32766; +32767)

In this case, the value sould be declared as unsigned [0; 65535].

I've opened an issue on OpenZwave https://github.com/OpenZWave/open-zwave/issues/1324.

I'll realized a code trick waiting for OpenZwave official answer

**Comment by jano42** [comment]
Fix in branch 2_0_0 (with workaround, waiting for OpenZWave official fix)
