### ISSUE TITLE
False Widget : Configuration

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#268]
The configuration section is not well placed into the window.

![image](https://user-images.githubusercontent.com/16737541/26870460-51300e44-4b70-11e7-9b78-8afef0d5574b.png)

Objects are returned instead of values for Serial port, etc ...

**Comment by jano42** [comment]
In fact the WIDGET configuration schema should not handle binding. (for the moment)

Actually the binding can be used for:
- getting serial ports
- getting network interfaces
- ask something to plugin (reserved to PLUGIN configuration)

In the future we can  implement binding in widget configuration, but actually this is not mandatory; because all binding cases are not usable with widgets.

**Comment by jano42** [comment]
Fixed in branch 2_0_0
