### ISSUE TITLE
[Equipement] no available widget to manage curtain

### ISSUE THREAD

**Issue by dgateau** [Yadoms/yadoms#272]
The curtain is a 3-states equipement : open/close/stop. this cannot be managed by switch, nor shutter  (see enum {Arrêter, ouvrir/monter, fermer/descendre} in img attached to issue #271)

**Comment by jano42** [comment]
Fixed in branch 2_0_0. Will be available in 2.0.0-rc.5

To test, you can deploy the curtain folder ( [sources/www/widgets/curtain](https://github.com/Yadoms/yadoms/tree/2_0_0/sources/www/widgets/curtain) ) into the matching folder next to your Yadoms executable (<path/of/yadoms>/www/widgets/curtain)
