### ISSUE TITLE
Unable to edit rule

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#361]
Unable to edit rule (Python + Blockly).

Problem seems to be JS-side in AutomationEditorManager.getAll function (line 27). We are looking for an interpreter of value yPython27, but only value ypython27 is available.

**Comment by jano42** [comment]
Not reproductible.
I've created a new rule with Blockly, the type is "yPython27" in database => can edit without problem

I've manually changed the type to "ypython27" in database => can edit without problem

@sgallou Make sure you have fully build script interpreter, and check your browser don't use any cache data (maybe a problem due to branch switching)

@sgallou ensure the package.json of scriptInterpreter (in your build folder) is the good one !

@sgallou If still in error, please post here a backup (database + scripts)

**Comment by sgallou** [comment]
Not reproductible today, maybe a browser cache side effect...
