### ISSUE TITLE
SQLite : Database backup

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#443]
With big database (>150 Mo), Yadoms take to much time to backupthe database and some plugins that's historize information during this time may fails, because of time out of the IPC communication.

**Comment by sgallou** [comment]
We have to try the [online backup](http://sqlite.org/c3ref/backup_finish.html#sqlite3backupinit) method of SQLite.

**Comment by jano42** [comment]
This can't be solved.
online backup do not work at all. (backup never ends and restart from 0 very often.) => the onlien backup have been really tested because the documentation tells it really match with our needs, but in reality it is not usable.

So the only remaining method is the 'locking' method which locks all access. And yes for long transfers some side effects may occurs.
