### ISSUE TITLE
[Chart] No lines in some configurations

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#514]
In 1Day-All or 1Week-Daily, points are well linked.

![image](https://user-images.githubusercontent.com/6855339/48866885-a7458180-edd4-11e8-8ce3-c39dc44a324f.png)

**Comment by jmberhault** [comment]
After analysing your base, you have values every 2 hours. The display is hour summary.

To disconnect portions of curve, like the following one : 
![image](https://user-images.githubusercontent.com/16737541/49828536-7382c980-fd8c-11e8-9371-fd78a35ee544.png)

After 1 hour (corresponding to the following value in continous sensor feeding), if no value is present, the widget chart add a null point, to cut the line (the display is much better as you could see as the plot below). If I do not this, you will have a straight line, that we could have when we display all values in 1 hour or day tab like this : 

![image](https://user-images.githubusercontent.com/16737541/49828770-fb68d380-fd8c-11e8-8582-4d64b4df1e3a.png)

I have not cut it when all values are displayed because, I dont know the sampling the the sensor. But I have add this for summary values, because, I assume you should have values for each hours, that the plugin doesn't comply.

So at this time, it's not a bug. It's a display feature.
