### ISSUE TITLE
[Dashboard] Language change also change password

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#69]
When changing only language, a new default password is saved. Can be dangerous !
If password was not edited, don't save it

Reported by: sgallou

**Comment by jano42** [comment]
Can't reproduce.

- [x] changing languages many times, never set a password
- [x] after having set a password, change only the language : password don't change
- [x] after having set a password, change the language but unckeck "authentication required", but the form reject to save it: 
- [x] after having set a password, change the language , then uncheck and check "authentication required" : password is not changed

Isssue is not reproductible.

@sgallou : you have reported this issue, do you remember how to reproduce ?

**Comment by sgallou** [comment]
It was a mistake, because after changing language, when password is already set, Chrome ask for remembering the new password, with a big string (my password was 4 characters length) :
![image](https://cloud.githubusercontent.com/assets/6855339/12732346/6f2d1dba-c935-11e5-8cef-e8f5cd2e252d.png)

It would be nice if browser don't ask for password change to be not confused.
