### ISSUE TITLE
RfxCom : duplicate device

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#87]
I've got a OWL Micro+ 180 with one current clamp.

After a few days (about one week), I've got 4 devices with thje same name CM180.

![image](https://cloud.githubusercontent.com/assets/3135683/13931743/fce0290a-efa4-11e5-9215-c61419b7f52e.png)

**Comment by sgallou** [comment]
It seems that's because on unsecured protocols (without CRC), so wrong messages are received and interpreted as new devices.
We can add a filter so a device must be seen 3 times in a short period to enable its declaration, but this filter must by applied only on unsecured protocols.
Actually waiting for the unsecured protocols list from the RFXCom constructor.

**Comment by sgallou** [comment]
Should be fixed by d19e48ae5151389bb2e2bb0c5a53b0d7eb81bf1b
